version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  wallet:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"